### ISSUE TITLE
mpz object has no attribute 'to_bytes'

### ISSUE THREAD

**Issue by dvvvsh** [10gic/btc-address-dump#8]
onathandoe@MacBook-Air-3 ~ % btc_address_dump 349571e1211343f73984b48e7d11d8695b806f7a9be347d14f1c78d3b7abacab
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/bin/btc_address_dump", line 8, in <module>
    sys.exit(run_main())
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/btc_address_dump/__init__.py", line 10, in run_main
    main_entry(sys.argv)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/btc_address_dump/btc_address_dump.py", line 169, in main_entry
    public_key_uncompressed = common_util.prikey_to_pubkey(private_key, compressed=False)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/btc_address_dump/common_util.py", line 88, in prikey_to_pubkey
    return pubkey_from_point_to_bytes(pubkey_point.x(), pubkey_point.y(), compressed)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/btc_address_dump/common_util.py", line 76, in pubkey_from_point_to_bytes
    x_bytes = x.to_bytes(32, byteorder='big')
AttributeError: 'mpz' object has no attribute 'to_bytes'

**Comment by 10gic** [comment]
Thanks for reporting this issue. This problem only occurs when gmpy2 is installed.
I have fixed it in version [0.4.1](https://pypi.org/project/btc-address-dump/0.4.1/), please upgrade it.

Ref:
https://bugs.gentoo.org/726882
https://github.com/spesmilo/electrum/issues/5927
